#!/bin/bash

echo "Fixing TypeScript errors in pages..."
echo "====================================="
echo ""
echo "Files to fix:"
echo "- src/pages/Account.tsx (deal.deal optional chaining)"
echo "- src/pages/DealDetail.tsx (deal.expiresAt, merchant type guards)"
echo "- src/pages/GroupDeals.tsx (groupDeal.deal, requiredParticipants optional)"
echo "- src/pages/Marketplace.tsx (listing.nft.deal optional, seller type guards)"
echo "- src/pages/MerchantDashboard.tsx (deal.discount optional)"
echo ""
echo "Total errors: ~60"
echo ""
echo "Strategy:"
echo "1. Add optional chaining for all .deal? accesses"
echo "2. Add type guards using getMerchantName/getMerchantLogo helpers"
echo "3. Add optional chaining for nullable fields"
echo "4. Use nullish coalescing for defaults"
