import { Promotion, Coupon, User, Merchant, MarketplaceListing, GroupDeal, Badge } from './api';

// Mock Merchants
export const mockMerchants: Merchant[] = [
  {
    id: 'm1',
    email: 'skyhigh@airlines.com',
    walletAddress: '0xmerchant1',
    name: 'SkyHigh Airlines',
    category: 'flights',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SA',
    totalCouponsCreated: 100,
    totalCouponsRedeemed: 45,
    isActive: true,
    averageRating: 4.8,
    totalRatings: 127,
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm2',
    email: 'paradise@resorts.com',
    walletAddress: '0xmerchant2',
    name: 'Paradise Resorts',
    category: 'hotels',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=PR',
    totalCouponsCreated: 50,
    totalCouponsRedeemed: 23,
    isActive: true,
    averageRating: 4.9,
    totalRatings: 89,
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm3',
    email: 'contact@legourmet.com',
    walletAddress: '0xmerchant3',
    name: 'Le Gourmet',
    category: 'restaurants',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=LG',
    totalCouponsCreated: 200,
    totalCouponsRedeemed: 67,
    isActive: true,
    averageRating: 4.7,
    totalRatings: 234,
    createdAt: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm4',
    email: 'sky@adventures.com',
    walletAddress: '0xmerchant4',
    name: 'Sky Adventures',
    category: 'experiences',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SA',
    totalCouponsCreated: 30,
    totalCouponsRedeemed: 12,
    isActive: true,
    averageRating: 5.0,
    totalRatings: 45,
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm5',
    email: 'fashion@boutique.com',
    walletAddress: '0xmerchant5',
    name: 'Fashion Boutique',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=FB',
    totalCouponsCreated: 150,
    totalCouponsRedeemed: 89,
    isActive: true,
    averageRating: 4.6,
    totalRatings: 178,
    createdAt: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm6',
    email: 'serenity@spa.com',
    walletAddress: '0xmerchant6',
    name: 'Serenity Spa',
    category: 'experiences',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SS',
    totalCouponsCreated: 80,
    totalCouponsRedeemed: 34,
    isActive: true,
    averageRating: 4.8,
    totalRatings: 92,
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    walletAddress: '0x1234...5678',
    address: '0x1234...5678',
    email: 'user@example.com',
    name: 'John Doe',
    role: 'user',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    totalPurchases: 67,
    totalRedemptions: 45,
    reputationScore: 850,
    reputation: 850,
    tier: 'Gold',
    reputationTier: 'Gold',
    badgesEarned: ['badge-1', 'badge-2'],
    badges: [
      {
        id: 'badge-1',
        badgeType: 'early_adopter',
        name: 'Early Adopter',
        description: 'Joined DealChain in the first month',
        imageUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=early',
        earnedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
        nftTokenId: '1001',
      },
      {
        id: 'badge-2',
        badgeType: 'deal_hunter',
        name: 'Deal Hunter',
        description: 'Claimed 50+ deals',
        imageUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=hunter',
        earnedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        nftTokenId: '1002',
      },
    ],
    totalSpent: 5420,
    dealsRedeemed: 67,
    stakingBalance: 1200,
    stakingRewards: 45.5,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    walletAddress: '0xmerchant...1234',
    address: '0xmerchant...1234',
    name: 'Luxury Hotels Inc',
    email: 'merchant@luxuryhotels.com',
    role: 'merchant',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=LH',
    totalPurchases: 0,
    totalRedemptions: 0,
    reputationScore: 950,
    reputation: 950,
    tier: 'Platinum',
    reputationTier: 'Platinum',
    badgesEarned: [],
    badges: [],
    totalSpent: 0,
    dealsRedeemed: 0,
    stakingBalance: 0,
    stakingRewards: 0,
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Mock Deals (Promotions)
export const mockDeals: Promotion[] = [
  {
    _id: '1',
    id: '1',
    onChainAddress: '0xpromo1',
    title: '50% Off Business Class Flights to Tokyo',
    description: 'Experience luxury travel with our exclusive business class deal. Includes lounge access, priority boarding, and premium meals.',
    imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    discountPercentage: 50,
    discount: 50,
    category: 'flights',
    merchant: mockMerchants[0],
    price: 1200,
    originalPrice: 2400,
    maxSupply: 100,
    currentSupply: 45,
    currency: 'USD',
    expiryTimestamp: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Tokyo, Japan',
    isActive: true,
    stats: {
      totalMinted: 45,
      totalRedeemed: 30,
      averageRating: 4.8,
      totalRatings: 127,
      totalComments: 45,
    },
    redemptionCount: 45,
    maxRedemptions: 100,
    rating: 4.8,
    reviewCount: 127,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    id: '2',
    onChainAddress: '0xpromo2',
    title: 'Luxury Resort Stay - 3 Nights in Bali',
    description: 'Unwind in paradise with our all-inclusive resort package. Private beach access, spa treatments, and gourmet dining included.',
    imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
    discountPercentage: 40,
    discount: 40,
    category: 'hotels',
    merchant: mockMerchants[1],
    price: 899,
    originalPrice: 1499,
    maxSupply: 50,
    currentSupply: 23,
    currency: 'USD',
    expiryTimestamp: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Bali, Indonesia',
    isActive: true,
    stats: {
      totalMinted: 23,
      totalRedeemed: 15,
      averageRating: 4.9,
      totalRatings: 89,
      totalComments: 32,
    },
    redemptionCount: 23,
    maxRedemptions: 50,
    rating: 4.9,
    reviewCount: 89,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    id: '3',
    onChainAddress: '0xpromo3',
    title: 'Michelin Star Dining Experience',
    description: 'Indulge in a 7-course tasting menu at our award-winning restaurant. Wine pairing included.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    discountPercentage: 35,
    discount: 35,
    category: 'restaurants',
    merchant: mockMerchants[2],
    price: 195,
    originalPrice: 300,
    maxSupply: 200,
    currentSupply: 67,
    currency: 'USD',
    expiryTimestamp: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'New York, NY',
    isActive: true,
    stats: {
      totalMinted: 67,
      totalRedeemed: 45,
      averageRating: 4.7,
      totalRatings: 234,
      totalComments: 89,
    },
    redemptionCount: 67,
    maxRedemptions: 200,
    rating: 4.7,
    reviewCount: 234,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    id: '4',
    onChainAddress: '0xpromo4',
    title: 'Hot Air Balloon Adventure',
    description: 'Soar above the clouds with our sunrise hot air balloon experience. Champagne breakfast included.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    discountPercentage: 30,
    discount: 30,
    category: 'experiences',
    merchant: mockMerchants[3],
    price: 210,
    originalPrice: 300,
    maxSupply: 30,
    currentSupply: 12,
    currency: 'USD',
    expiryTimestamp: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Cappadocia, Turkey',
    isActive: true,
    stats: {
      totalMinted: 12,
      totalRedeemed: 8,
      averageRating: 5.0,
      totalRatings: 45,
      totalComments: 23,
    },
    redemptionCount: 12,
    maxRedemptions: 30,
    rating: 5.0,
    reviewCount: 45,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '5',
    id: '5',
    onChainAddress: '0xpromo5',
    title: 'Designer Fashion Sale - Up to 60% Off',
    description: 'Shop the latest collections from top designers. Limited time offer on selected items.',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    discountPercentage: 60,
    discount: 60,
    category: 'shopping',
    merchant: mockMerchants[4],
    price: 400,
    originalPrice: 1000,
    maxSupply: 150,
    currentSupply: 89,
    currency: 'USD',
    expiryTimestamp: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Milan, Italy',
    isActive: true,
    stats: {
      totalMinted: 89,
      totalRedeemed: 60,
      averageRating: 4.6,
      totalRatings: 178,
      totalComments: 67,
    },
    redemptionCount: 89,
    maxRedemptions: 150,
    rating: 4.6,
    reviewCount: 178,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '6',
    id: '6',
    onChainAddress: '0xpromo6',
    title: 'Spa Day Package - Full Body Massage & Facial',
    description: 'Relax and rejuvenate with our premium spa package. Includes massage, facial, and access to thermal pools.',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
    discountPercentage: 45,
    discount: 45,
    category: 'experiences',
    merchant: mockMerchants[5],
    price: 165,
    originalPrice: 300,
    maxSupply: 80,
    currentSupply: 34,
    currency: 'USD',
    expiryTimestamp: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Los Angeles, CA',
    isActive: true,
    stats: {
      totalMinted: 34,
      totalRedeemed: 20,
      averageRating: 4.8,
      totalRatings: 92,
      totalComments: 41,
    },
    redemptionCount: 34,
    maxRedemptions: 80,
    rating: 4.8,
    reviewCount: 92,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Mock NFTs (Coupons)
export const mockNFTs: Coupon[] = [
  {
    _id: 'nft1',
    id: 'nft1',
    onChainAddress: '0xcoupon1',
    couponId: 1001,
    tokenId: '1001',
    nftMint: '0xmint1',
    promotion: mockDeals[0],
    dealId: '1',
    deal: mockDeals[0],
    owner: '0x1234...5678',
    merchant: mockMerchants[0].id,
    discountPercentage: 50,
    expiryTimestamp: mockDeals[0].expiryTimestamp,
    isRedeemed: false,
    isListed: false,
    purchasedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    transferHistory: [],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'nft2',
    id: 'nft2',
    onChainAddress: '0xcoupon2',
    couponId: 1002,
    tokenId: '1002',
    nftMint: '0xmint2',
    promotion: mockDeals[1],
    dealId: '2',
    deal: mockDeals[1],
    owner: '0x1234...5678',
    merchant: mockMerchants[1].id,
    discountPercentage: 40,
    expiryTimestamp: mockDeals[1].expiryTimestamp,
    isRedeemed: true,
    redeemedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isListed: false,
    purchasedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    transferHistory: [],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'nft3',
    id: 'nft3',
    onChainAddress: '0xcoupon3',
    couponId: 1003,
    tokenId: '1003',
    nftMint: '0xmint3',
    promotion: mockDeals[2],
    dealId: '3',
    deal: mockDeals[2],
    owner: '0x1234...5678',
    merchant: mockMerchants[2].id,
    discountPercentage: 35,
    expiryTimestamp: mockDeals[2].expiryTimestamp,
    isRedeemed: false,
    isListed: true,
    listingPrice: 220,
    resalePrice: 220,
    purchasedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    transferHistory: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Mock Marketplace Listings
export const mockListings: MarketplaceListing[] = [
  {
    _id: 'listing1',
    id: 'listing1',
    onChainAddress: '0xlisting1',
    coupon: mockNFTs[2],
    nft: mockNFTs[2],
    seller: mockUsers[0],
    price: 220,
    currency: 'USD',
    listedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Group Deals
export const mockGroupDeals: GroupDeal[] = [
  {
    id: 'group1',
    onChainAddress: '0xgroup1',
    promotion: mockDeals[0],
    deal: mockDeals[0],
    targetParticipants: 50,
    requiredParticipants: 50,
    currentParticipants: 32,
    status: 'active',
    tiers: [
      { participants: 10, discountPercentage: 55, discount: 55 },
      { participants: 25, discountPercentage: 60, discount: 60 },
      { participants: 50, discountPercentage: 65, discount: 65 },
    ],
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'group2',
    onChainAddress: '0xgroup2',
    promotion: mockDeals[1],
    deal: mockDeals[1],
    targetParticipants: 30,
    requiredParticipants: 30,
    currentParticipants: 18,
    status: 'active',
    tiers: [
      { participants: 10, discountPercentage: 45, discount: 45 },
      { participants: 20, discountPercentage: 50, discount: 50 },
      { participants: 30, discountPercentage: 55, discount: 55 },
    ],
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Legacy type aliases for compatibility
export type Deal = Promotion;
export type NFT = Coupon;
